[package]
name = "chatserver"
version = "0.1.0"
authors = ["Gexon <alimgan@gmail.com>"]

[dependencies]
mio = "0.6.0"
byteorder = "0.5.3"
slab = "0.3.0"
log = "0.3.6"
env_logger = "0.3.5"
mysql = "*"
time = "0.1.35"